name: Update Database & Deploy

on:
  push:
    branches:
      - main  # Или master, если ваша ветка называется так

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Обновили до v4

      - name: Set up Python
        uses: actions/setup-python@v5  # Обновили до v5
        with:
          python-version: '3.9'

      - name: Generate Database
        run: python generate.py

      - name: Setup Pages
        uses: actions/configure-pages@v5  # Обновили до v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Обновили до v3 (это исправит ошибку)
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Обновили до v4
